// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpenApiGenerator from "./OpenApiGenerator.res.mjs";

let demoSchema = "{\n  \"openapi\": \"3.0.4\",\n  \"info\": {\n    \"title\": \"Pet Store API\",\n    \"version\": \"1.0.0\"\n  },\n  \"components\": {\n    \"schemas\": {\n      \"Pet\": {\n        \"type\": \"object\",\n        \"required\": [\"name\", \"photoUrls\"],\n        \"properties\": {\n          \"id\": {\n            \"type\": \"integer\",\n            \"format\": \"int64\"\n          },\n          \"name\": {\n            \"type\": \"string\",\n            \"example\": \"doggie\"\n          },\n          \"photoUrls\": {\n            \"type\": \"array\",\n            \"items\": {\n              \"type\": \"string\"\n            }\n          },\n          \"status\": {\n            \"type\": \"string\",\n            \"enum\": [\"available\", \"pending\", \"sold\"]\n          }\n        }\n      },\n      \"Category\": {\n        \"type\": \"object\",\n        \"properties\": {\n          \"id\": {\n            \"type\": \"integer\",\n            \"format\": \"int64\"\n          },\n          \"name\": {\n            \"type\": \"string\"\n          }\n        }\n      }\n    }\n  }\n}";

function demo() {
  let msg = OpenApiGenerator.generateModule(demoSchema);
  if (msg.TAG === "Ok") {
    console.log("Generated ReScript types:");
    console.log("=" + "=".repeat(50));
    console.log(msg._0);
    console.log("=" + "=".repeat(50));
    return;
  }
  console.log("Error: " + msg._0);
}

demo();

export {
  demoSchema,
  demo,
}
/*  Not a pure module */
