// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Url from "url";
import * as Path from "path";
import * as OpenApiGenerator from "./OpenApiGenerator.res.mjs";

function getCurrentDir() {
  let importMetaUrl = import.meta.url;
  return Path.dirname(Url.fileURLToPath(importMetaUrl));
}

function generatePetstoreTypes() {
  console.log("🚀 Starting Petstore type generation...");
  try {
    let currentDir = getCurrentDir();
    let petstoreSchemaPath = Path.resolve(currentDir, "../examples/petstore/openapi.json");
    console.log("📁 Reading Petstore schema from: " + petstoreSchemaPath);
    if (!Fs.existsSync(petstoreSchemaPath)) {
      console.error("❌ Petstore schema file not found at: " + petstoreSchemaPath);
      ((process.exit(1)));
    }
    let openApiJsonString = Fs.readFileSync(petstoreSchemaPath, "utf8");
    console.log("✅ Read " + openApiJsonString.length.toString() + " characters from schema file");
    console.log("🔄 Generating ReScript module...");
    let msg = OpenApiGenerator.generateModule(openApiJsonString);
    if (msg.TAG === "Ok") {
      let moduleCode = msg._0;
      console.log("✅ Module generation successful!");
      let testProjectSrcPath = Path.resolve(currentDir, "../test-generated-types/src");
      let outputFilePath = Path.join(testProjectSrcPath, "GeneratedPetstoreTypes.res");
      console.log("📝 Writing generated types to: " + outputFilePath);
      if (!Fs.existsSync(testProjectSrcPath)) {
        console.log("📁 Creating src directory...");
        Fs.mkdirSync(testProjectSrcPath, {
          recursive: true
        });
      }
      Fs.writeFileSync(outputFilePath, moduleCode);
      console.log("✅ Successfully generated Petstore types!");
      console.log("📄 Generated " + moduleCode.split("\n").length.toString() + " lines of ReScript code");
      return;
    }
    console.error("❌ Type generation failed: " + msg._0);
    return (process.exit(1));
  } catch (exn) {
    console.error("❌ Error: Failed to generate types");
    return (process.exit(1));
  }
}

generatePetstoreTypes();

export {
  getCurrentDir,
  generatePetstoreTypes,
}
/*  Not a pure module */
