// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";

Ava("basic string equality", t => {
  t.is("hello", "hello");
});

Ava("basic number equality", t => {
  t.is(42, 42);
});

Ava("array length", t => {
  let arr = [
    1,
    2,
    3
  ];
  t.is(arr.length, 3);
});

Ava("promise resolution", t => Promise.resolve("success").then(result => {
  t.is(result, "success");
}));

/*  Not a pure module */
