name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build ReScript
        run: yarn res:build

      - name: Run tests
        run: yarn test

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ There are uncommitted changes after build:"
            git status --porcelain
            exit 1
          else
            echo "✅ No uncommitted changes after build"
          fi

  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check ReScript formatting
        run: yarn res:build && yarn res:format:check

  type-generation:
    name: Type Generation Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build main project
        run: yarn res:build

      - name: Generate Petstore types
        run: node src/GeneratePetstoreTypes.res.mjs

      - name: Install test project dependencies
        run: cd test-generated-types && yarn install --frozen-lockfile

      - name: Compile generated types
        run: cd test-generated-types && npx rescript

      - name: Check for uncommitted generated files
        run: |
          if [ -n "$(git status --porcelain test-generated-types/src/GeneratedPetstoreTypes.res)" ]; then
            echo "❌ Generated file has uncommitted changes after regeneration:"
            git diff test-generated-types/src/GeneratedPetstoreTypes.res
            echo ""
            echo "Please run 'node src/GeneratePetstoreTypes.res.mjs' locally and commit the updated file."
            exit 1
          else
            echo "✅ Generated file is up to date"
          fi

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [test, lint, type-generation]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clean build
        run: yarn res:clean

      - name: Build from scratch
        run: yarn res:build

      - name: Verify build artifacts
        run: |
          echo "✅ Build completed successfully"
          echo "Generated files:"
          find src __tests__ -name "*.res.mjs" -type f | head -10
